baseURL = "https://mohamedkari.github.io/blog.mkari.de/"
languageCode = "en-us"
theme = "pickles"
copyright = "&copy; Mohamed Kari&nbsp;•&nbsp;All rights reserved.&nbsp;•&nbsp;2020-2024"
paginate = 100

[markup.goldmark.renderer]
unsafe= true

[params]
  github = "MohamedKari"
  linkedin = "mohamedkari"
  authorwebsite = "https://mkari.de/"
  author = "Mohamed Kari"
  avatar = "/static/avatar.jpeg"
  bio = "PhD Student in Machine Learning at Porsche and at University of Duisburg-Essen"
  contact = "mailto:mo@mkari.de"